# .air.toml

# thư mục gốc của project
root = "."
# thư mục build tạm
tmp_dir = "tmp"

[build]
# Lệnh build: chỉ build server, không generate swagger trong vòng lặp
cmd = "go build -o ./tmp/main.exe ./cmd/server"
bin = "tmp/main.exe"
kill_delay = "500ms"

[proc]
kill_cmd = "taskkill /F /IM main.exe"

# extensions được watch
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
# thư mục bỏ qua
exclude_dir = ["assets", "docs", "tmp", "vendor", ".git", "bin"]
# files to exclude
exclude_file = ["docs/docs.go", "docs/swagger.json", "docs/swagger.yaml", "cmd/server/main.go"]

# delay reload (ms)
delay = 3000

[log]
# log kèm timestamp
time = true
