# .air.toml

# thư mục gốc của project
root = "."
# thư mục build tạm
tmp_dir = "tmp"

[build]
# Lệnh build: luôn generate swagger trước rồi build server
cmd = "swag init -g cmd/server/main.go --parseDependency --parseInternal && go build -o ./tmp/server ./cmd/server"
bin = "tmp/server"
full_bin = "./tmp/server"

# extensions được watch
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
# thư mục bỏ qua
exclude_dir = ["assets", "docs", "tmp", "vendor"]

# delay reload (ms)
delay = 1000

[log]
# log kèm timestamp
time = true
