services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  
  nats:
    image: nats:2
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - mynetwork
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: file_converter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d file_converter"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DEV_MODE: "true"
      REDIS_ADDR: "redis:6379"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "123"
      DB_NAME: "file_converter"
    depends_on:
      - redis
      - nats
      - postgres
    volumes:
      - ./127.0.0.1.pem:/app/127.0.0.1.pem
      - ./127.0.0.1-key.pem:/app/127.0.0.1-key.pem
      - ./entrypoint.sh:/app/entrypoint.sh
      # Thiếu những volume quan trọng này:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./docs:/app/docs
      - .:/app
    networks:
      - mynetwork
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    environment:
      REDIS_ADDR: "redis:6379"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "123"
      DB_NAME: "file_converter"
    depends_on:
      - redis
      - nats
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:


# ADD THIS SECTION - Volume definitions
volumes:
  postgres_data:
    driver: local