services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nats:
    image: nats:2
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Secret123
    ports:
      - "5050:80"
    networks:
      - mynetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: file_converter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d file_converter"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mynetwork:

volumes:
  postgres_data:
    driver: local
  pgadmin-data:
    driver: local
