basePath: /api
host: localhost:8081
info:
  contact:
    email: you@example.com
    name: Your Name
  description: Upload & convert files asynchronously via Asynq queue.
  title: File Converter API 121
  version: "1.0"
paths: {}
swagger: "2.0"
